### ISSUE TITLE
More information around the depedencies.

### ISSUE THREAD

**Issue by RKALM** [lavdimimeri/Fullstack-JavaSpringBootAndReact-#1]
Hello man,
Is it possible to add, a few information about your setup in the readme?
Just information about what java version you are using, and what, (and how of course), you had to install, just to make it easy for someone to jump, to help you with your project.
With my best regards,
Robert

**Comment by lavdimimeri** [comment]
Hello man,

Sorry for the delay to response!
You do not need to asks such things man, just go and do whatever you want so I can learn from you 🤙

Best regards
Lavdim







11 feb. 2023 kl. 16:49 skrev Robert Kristian Alm ***@***.***>:

﻿

Hello man,
Is it possible to add, a few information about your setup in the readme?
Just information about what java version you are using, and what, (and how of course), you had to install, just to make it easy for someone to jump, to help you with your project.
With my best regards,
Robert

**Comment by RKALM** [comment]
Thank you man!
